title: Brenden J. Moore # your name (or website title) here
logo: "headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. of Business Analytics Candidate at The George Washington University 
  <br><br>
  B.S. of Business Administration in Finance from the University of Denver 
  <br><br>
  <a href="https://www.linkedin.com/in/brendenjmoore/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-LLJ112K3ZN # your Google Analytics tracking ID here
